import './globals.css'
import type { Metadata } from 'next'
import { DM_Sans } from 'next/font/google'
import { notFound } from 'next/navigation';
import { GoogleAnalytics } from '@next/third-parties/google'

const locales = ['en', 'es'];

const inter = DM_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Merliteam',
  description: 'Generated by create next app',
}

type LocaleLayoutProps = {
  children: React.ReactNode;
  params: {
    locale: string;
  };
};

export default function LocaleLayout({ children, params: { locale } }: LocaleLayoutProps) {
  if (!locales.includes(locale as any)) notFound();

  return (
    <html lang={locale}>
      <head>
        <title>Merliteam</title>
        <link rel="icon" href="/MerliTeamLogoRedondo.svg" sizes="32x32"/>
        <meta name="google-site-verification" content="flPF7T6iV0dSSs_z92wbewTx8hnLtpNBtjQvVAHDaJM"/>
      </head>
      <body className={`${inter.className} text-merli-gray-light bg-gradient-radial`}>{children}</body>
      <GoogleAnalytics gaId="G-1WHF6KC60T" />
    </html>
  )
}
